remote_theme: jeromelachaud/grayscale-theme
# Site settings
title: Roll your beauty
email: hello@myrelaxjoy.com
url: https://www.myrelaxjoy.com/
description: "Growing old is mandatory, looking old is optional"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#297e5b'
  links: '#219ab3'

# Footer settings
footer: RELAX & JOY

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook-messenger
    url: m.me/myrelaxjoy
    alias: messenger
  - title: facebook
    url: https://www.facebook.com/myrelaxjoy
    alias: facebook


# Build settings
markdown: kramdown
permalink: pretty

